image: node:latest

stages:
  - setup

setup_and_deploy:
  stage: setup
  script:
    - npm ci
    - npm run pre-commit
    - node_modules/.bin/serverless config credentials -p aws -k $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY
    - npm run build
    - npm run deploy:stage
